apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
  labels:
    app: service-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-template
  template:
    metadata:
      labels:
        app: service-template
    spec:
      containers:
        - name: service-template
          image: victorf13/service-template:5e5ebc8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
